### ISSUE TITLE
[BUG] Incorrect wording in explanations of lesson 4.

### ISSUE THREAD

**Issue by lewiswhe** [dqrobotics/learning-dqrobotics-in-matlab#4]
**************************
### Code of Conduct
_By submitting this report you automatically agree that you've read and accepted the following conditions._ 
- Support for DQ Robotics is given voluntarily and it's not the developers' role to educate and/or convince anyone of their vision.
- Any possible response and its timeliness will be based on the relevance, accuracy, and politeness of a request and the following discussion.
- If a DQ Robotics member replies, the user must let them know if their response solves their issue or not. 
- Any suggestion/advice/request made by anyone, as well intentioned as they might be, might not be incorporated into DQ Robotics.
*************************
**Bug description**
1. In the Notation section of Lesson 4, p and t are stated to be dual quaternions, instead of quaternions.

2. In the What we have seen so far > Reference frames and pose transformations, the dot product is used rather than multiplication in the definition of a unit dual quaternion.

**Expected**
Removal of the word "dual" and removal of the "." in the equation

**Comment by bvadorno** [comment]
Thanks, @lewiswhe. 

I assigned @mmmarinho to this issue because he designed the lessons, but let's rectify some misconceptions. Every quaternion is a dual quaternion, although not all dual quaternion is a quaternion. See Section 2.2 of [1], notably the explanation after Eq. (2.2.1).

Multiplication and dot product (Eq. 2.2.4 of [1]) are different types of operations. Rigid motions are propagated through regular multiplications. Dot products (sometimes called inner products) are usually used to operate on Plücker lines. 

I suggest that you read [1] together with those MATLAB lessons. My 15+ years of experience working on this theory tells me that If you don't get a strong base now, you'll have many gaps that will come back to bite you.

Kind regards,
Bruno

[1] B. V. Adorno, “Robot Kinematic Modeling and Control Based on Dual Quaternion Algebra -- Part I: Fundamentals,” Federal University of Minas Gerais, 2017. [Online]. Available: https://hal.archives-ouvertes.fr/hal-01478225v1

**Comment by mmmarinho** [comment]
Thanks, @lewiswhe. 

I've fixed the typos you mentioned. The "dot" product was caused by a font problem with Live scripts propagating font where it shouldn't and I've correctly replaced it with a space. 

Thanks for the reference and the advice as welll @bvadorno.
